/**
 * HowItWorks — numbered narrative with vertical rail.
 *
 * Tighter type scale on the section h2 (was text-3xl md:text-4xl, now drops
 * to a Razorpay-style mid-size). Sigil added (§ 01) to lend editorial weight.
 */
import { motion, useReducedMotion } from "framer-motion";
import { SectionKicker } from "./SectionKicker";

const STEPS = [
  {
    n: "01",
    title: "Set up the role",
    body: "Pick a finance role — controllership, tax, audit, or consulting. A Big-4 calibrated 10-skill blueprint appears in seconds. Edit, accept, ship.",
    detail: "Blueprint generated by an agent trained on 200+ India CA-firm job descriptions.",
  },
  {
    n: "02",
    title: "Applicants take the assessment",
    body: "A 20-minute structured AI interview probes depth on GST, Ind-AS, transfer pricing, controllership. India time-slot, audio-led, desktop-first.",
    detail: "Applicants get the prep guide up front. No surprise questions.",
  },
  {
    n: "03",
    title: "You read the Talent Analysis Graph",
    body: "A radial skill graph with per-skill evidence, scores, and a clear hireability call. Sort, compare, decide in minutes.",
    detail: "Every score links back to the transcript line that produced it.",
  },
];

export function HowItWorks() {
  const reduce = useReducedMotion();
  return (
    <section id="how-it-works" className="bg-paper scroll-mt-20">
      <div className="max-w-6xl mx-auto px-6 py-20 md:py-24">
        <div className="mb-12 max-w-2xl">
          <SectionKicker label="How it works" sigil="§ 01" />
          <h2 className="text-2xl md:text-[28px] lg:text-[32px] font-semibold text-ink tracking-[-0.01em] leading-tight">
            Three steps from job-open to shortlist.
          </h2>
        </div>
        <div className="relative">
          <div
            aria-hidden
            className="absolute left-[19px] top-3 bottom-3 w-px bg-rule hidden md:block"
          />
          <ol className="space-y-12">
            {STEPS.map((s, i) => (
              <motion.li
                key={s.n}
                className="relative grid md:grid-cols-[40px_1fr] gap-6 items-start"
                initial={reduce ? { opacity: 1, y: 0 } : { opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{ duration: 0.5, delay: i * 0.08, ease: [0.16, 1, 0.3, 1] }}
              >
                <div className="font-mono text-sm font-semibold tabular-nums text-gold-ink bg-paper border border-rule rounded-sm w-10 h-10 grid place-items-center">
                  {s.n}
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-ink tracking-tight mb-2">
                    {s.title}
                  </h3>
                  <p className="text-base text-ink-soft leading-relaxed max-w-[65ch] mb-2">
                    {s.body}
                  </p>
                  <p className="text-xs text-muted font-mono leading-relaxed">
                    {s.detail}
                  </p>
                </div>
              </motion.li>
            ))}
          </ol>
        </div>
      </div>
    </section>
  );
}
